version: '3.1'

services:
  redaktion:
    container_name: redaktion
    build:
      context: ./redaktions-app/
      dockerfile: ./dev.Dockerfile
    ports:
      - '3001:3000'

  user-app:
    container_name: user-app
    build:
      context: ./candymat-user-app/
      dockerfile: ./dev.Dockerfile
    ports:
      - "8080:8080"

  postgres:
    image: candymat-postgres:11.5
    build:
      dockerfile: ./Dockerfile
      context: ./backend/
    env_file: ./backend/.env-backend
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend

  graphql:
    restart: always
    image: graphile/postgraphile
    depends_on:
      - postgres
    env_file: ./backend/.env-backend
    ports:
      - "5000:5000"
    command: ["--connection", $DATABASE_URL, "--host", "0.0.0.0", "--port", "5000", "--schema", "candymat_data", "--watch"]
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend: