version: '3.1'

services:
  postgres:
    image: candymat-postgres:11.5
    build:
      dockerfile: ./Dockerfile.postgres
      context: ./backend/
    env_file: ./backend/.env-backend
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend

  graphql:
    restart: always
    image: graphile/postgraphile
    depends_on:
      - postgres
    env_file: ./backend/.env-backend
    ports:
      - "5000:5000"
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--port", "5000", "--schema", "candymat_data", "--watch"]
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend: